---
# camera
- hosts: camera
  tasks:
  - name: update cache
    apt: update_cache=yes cache_valid_time=3600
  - name: update system
    apt: upgrade=dist
  - name: ensure rabbitmq server is installed
    apt: pkg=rabbitmq-server state=latest
  - name: ensure ruby is installed
    apt: pkg=ruby,ruby-dev,bundler state=latest
  - name: ensure tmux is installed
    apt: pkg=tmux state=latest
  - name: ensure ntpdate is installed
    apt: pkg=ntpdate state=latest
  - name: ensure ufw is installed
    apt: pkg=ufw state=latest

  # - authorized_key: user={{ ansible_ssh_user}} key="{{ lookup('file', './phenology.pub') }}"
  # - authorized_key: user={{ ansible_ssh_user}} key="{{ lookup('file', './granby.pub') }}"

  - name: copy camera files
    copy: src={{ item }} dest=/home/{{ansible_ssh_user}}/{{ item }}camera.rb }}
    with_items:
      - "camera.rb"
      - "camera.sh"
      - "night.rb"
      - "Gemfile"

  - include_vars: password.yml
  - rabbitmq_user: user=pi
                 password={{password}}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

  - name: allow ssh in ufw firewall
    ufw: rule=allow port=22
  - name: configure allowed access
    ufw: rule=allow src={{item}}
    with_items:
      - 192.231.113.231
      - 192.108.188.184
      - 192.231.113.159
      - 192.231.113.218

  - name: turn uwf logging off
    ufw: logging=off
  - name: enable firewall
    ufw: state=enabled

  - name: install RubySunrise gem
    gem: name=RubySunrise state=latest user_install=no 
  - name: install amq protocol gem
    gem: name=amq-protocol state=latest user_install=no
  - name: install amqp gem
    gem: name=amqp state=latest user_install=no
  - name: install tzinfo gem
    gem: name=tzinfo state=latest user_install=no

  # create images directory
  # add stuff to crontab
  - cron: name="reboot" minute="0" hour="2" job="reboot now > /dev/null"


