---
# camera
- hosts: camera
  tasks:
  - name: rabbitmq
    apt: pkg=rabbitmq-server state=latest
  - apt: pkg=ruby-dev state=latest

  - authorized_key: user={{ ansible_ssh_user}} key="{{ lookup('file', './phenology.pub') }}"
  - authorized_key: user={{ ansible_ssh_user}} key="{{ lookup('file', './granby.pub') }}"

  - copy: src=camera.rb dest=/home/{{ansible_ssh_user}}/camera.rb 
  - copy: src=Gemfile dest=/home/{{ansible_ssh_user}}/Gemfile

  - include_vars: password.yml
  - rabbitmq_user: user=pi
                 password={{password}}
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present

  - ufw: rule=allow src=192.231.113.231


  - name: bundle ruby gems
    gem: name=RubySunrise state=latest

  - gem: name=bunny state=latest
